# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c1f50949cc4609a3d6706f73922b81df7d05c97d418dc0207ccae4d15c581d7be5f906cee90972b99aa609f3ab299b0e826361ff38430512b831c4b07e32f36

test:
  secret_key_base: 91c8632d3e487ea7d7c3ea541249d45ea15ae32173e83df799ad974378f079841fd34ccbd72296725886b3e020fd3531aaab8cbd4afc1fc82243dce8bb57d5e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
